jgc_user_homepage:
    path:   /hello/{name}
    defaults:   { _controller: JGCUserBundle:Default:index }

jgc_user_index:
    path:   /user/index
    defaults:   { _controller: JGCUserBundle:User:index }

jgc_user_add:
    path:   /user/add
    defaults:   { _controller: JGCUserBundle:User:add }

jgc_user_create:
    path:   /user/create
    defaults:   { _controller: JGCUserBundle:User:create }
    methods: POST

jgc_user_edit:
    path:   /user/edit/{id}
    defaults:   { _controller: JGCUserBundle:User:edit }

jgc_user_view:
    path:   /user/view/{id}
    defaults:   { _controller: JGCUserBundle:User:view }

jgc_user_delete:
    path:   /user/delete/{id}
    defaults:   { _controller: JGCUserBundle:User:delete }

jgc_user_redirect_add:
    path: /user/create
    defaults:
        _controller: JGCUserBundle:User:add
        path: /user/add
        permanent: true
